name: big
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - brotli==1.2.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.0
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.2
      - cuda-python==13.0.3
      - cycler==0.12.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - gevent==25.9.1
      - geventhttpclient==2.3.7
      - greenlet==3.2.4
      - grpcio==1.67.1
      - idna==3.11
      - importlib-resources==6.5.2
      - jittor==1.3.10.0
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - multidict==6.7.0
      - numpy==1.26.4
      - opencv-python==4.8.0.74
      - packaging==25.0
      - pandas==2.3.3
      - perf-analyzer==0.1.0
      - pillow==11.3.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - propcache==0.4.1
      - protobuf==5.29.5
      - psutil==7.1.3
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-rapidjson==1.23
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.17.0
      - tqdm==4.67.1
      - tritonclient==2.63.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zope-event==6.0
      - zope-interface==8.0.1
prefix: /home/oisdoaiu/miniconda3/envs/big
